src/tcompiler.cpp
src/tcwrapper.cpp
src/terralib.lua

I wanted to interface better with the GLEW library like mentioned in #71, so I did my best to implement the importing of global variables.  It seems to work for both simple cases like
```lua
C = terralib.includec("stdio.h")
terra main()
C.fprintf(C.stdio, "Hello, world!")
end
main()
```
as well as with more complicated cases, like global function pointers.  (the KeepVarLive seems to be only necessary for function pointers, for some reason.)  If there's anything more complicated that I'm missing, I'm not aware of it.
I've never worked with the LLVM or Lua APIs before, so if you have the time, I'd appreciate it if you could look over my changes.  Thanks.

Add support for importing external global variables from C

---

src/tcwrapper.cpp

I assume the problem has the same root on the various *nixs where it has
occured. The problem was the comparison of the `std::error_code` and
`std::errc` on this platform. Creating an "real" `error_code` object to
compare against fixes the problem. Still working on my mac after this change.
fixes #137

Fixed not finding internalizedfiles on Mint 17.2

---

Makefile
src/tcuda.cpp

1) It's common for CUDA_HOME to be something other than /usr/local/cuda, but the ENABLE_CUDA check was hardcoded.
2) g++ gets confused about which symbol's type you're trying to grab in tcuda.cpp - an explicit global namespace cleans it up.
Both changes work ok on my mac laptop too.

couple build fixes for terra+cuda on Linux

---

Makefile

This is so that I can host a custom LuaJIT mirror to work around luajit.org unavailability, etc.

Allow LuaJIT to be configured by the user.

---

Makefile
src/lj_strscan.c
src/lj_strscan.h
src/treadnumber.c

Tested on Linux (gcc 4.8.5) and MacOS (clang 3.5.2)

 copy lj_strscan.[ch] from LuaJIT source to eliminate source-level coupling

---

api.md

I was just trying out the entrymissing capability for the first time and at first I tried using a lua function rather than a macro, reading the terra source showed me that it had to be a macro, but maybe worth having in the api reference.

add entrymissing must be macro

---

src/terralib.lua

Fixes a problem in error reporting:
```
src/terralib.lua:388: attempt to perform arithmetic on local 'depth' (a nil value)
stack traceback:
src/terralib.lua:388: in function 'finishandabortiferrors'
src/terralib.lua:1113: in function <src/terralib.lua:1109>
```

Add missing depth arg to finishandabortiferrors call

---

src/lparser.cpp
src/tcompiler.cpp
src/tdebug.cpp

Eliminates a few compiler warnings that have been bugging me for a while.  No functional changes.

eliminate compiler warnings in build

---

Makefile

The `-E` flag for sed is BSD-specific. It is supported for backwards compatibility only in certain newer versions of GNU Sed, but not all versions. (Furthermore, this support is [undocumented](https://stackoverflow.com/a/3139925/188046).)
This patch checks that `sed -E` actually works, and otherwise falls back to `sed -r` which is the GNU Sed version of this flag.

Fix for non-BSD Sed

---

.gitignore
Makefile
src/tcompiler.cpp
src/tcwrapper.cpp
src/tdebug.cpp
src/terralib.lua
tests/stattest.t

The first change allows terra to build and run, at least in the FreeBSD virtual machine I'm using.
I built with clang 3.8, and gmake is required (the BSD version of make does not like the Makefiles at all).
There is no CUDA for FreeBSD, so this is CPU only.  One test (stattest.t) is disabled because FreeBSD's
sys/stat.h uses bit fields in `struct stat`, which confuses terra.
The second two changes address an issue that may or may not be specific to my VM.  Despite the OS
claiming that the CPU supports AVX instructions, I get a SIGILL in many tests because llvm happily
generates AVX instructions.  The workaround involves a general-purpose change that is needed to actually get feature flags into MCJIT and clang (for include_c), followed by a ifdef-protected change
that makes "-avx" the …

attempt at adding support for FreeBSD

---

src/main.cpp

Problem:
- the doerror() function in main.cpp prints errors to stdout and
this interferes when scripting with terra
- when using terra combined with unix piping stdout and stderr get
mixed into stdout and this might cause problems to downstream
commands in the linux pipeline that aren't expecting error messages
in their stdin stream
Solution:
- change error-printing stream to stderr

Fix to print errors to stderr, instead of stdout

---

src/tcompiler.cpp
src/terralib.lua
tests/nontemporal.t

Three fixes:
1) Generate !nontemporal metadata for loads as well.  (This is allowed in the LLVM IR, although the x86 code generators seem to ignore it for now.)
2) Do not generate the !nontemporal metadata if the "nontemporal" attribute is false.
3) Allow the attributes for attrload/attrstore to be provided via a variable holding a lua table in addition to the "immediate" constructor syntax.

several fixes for nontemporal loads and stores

---

release/include/terra/terra.h
src/main.cpp

Problem:
- terra does not support command line option -e
- this makes it difficult to use terra as a drop-in replacement for other lua implementations when doing scripting
- it is useful to evaluate/run a terra chunk of code in the command line
Solution:
- add a new command-line option -e with the same semantics as other lua implementations
Example: ./terra -e 'c = terralib.includec("stdio.h"); c.printf("Hello World!\n")'

:art: :new: Command line option -e

---

src/tllvmutil.cpp

Set linkage to external linkage when the function is existed in module #273

Update tllvmutil.cpp to solve issue

---

src/cudalib.lua
src/tcuda.cpp
src/terralib.lua

When `saveobj`-ing a CUDA module, Terra will now automatically find libdevice (an LLVM bitcode library that contains math functions for GPUs) and link it in. Because we now set the correct target for CUDA modules, LLVM knows to run the appropriate passes (in particular NVVMReflect, which will desugar the `__nvvm_reflect` pseudo-instruction, which is used in libdevice for CUDA versions 9.0 and up).
The user (still) needs to manually `linkllvm` libdevice, if they want to run CUDA code on the terra process.

Handle libdevice properly on CUDA 9.0+

---

src/tcompiler.cpp
src/terralib.lua

Relocated from https://github.com/StanfordLegion/terra/pull/1.
The new API is as follows:
terralib.saveobj(filename, [filetype], functiontable, [arguments, target, optimize])
where optimize is a boolean value. The default is true i.e. enable optimizations.

Extend terralib.saveobj API to allow disabling LLVM optimizations

---

.travis.yml
Makefile
src/llvmheaders.h
src/llvmheaders_60.h
src/tcompiler.cpp
src/tcuda.cpp
src/tcwrapper.cpp
src/tinline.cpp
src/tllvmutil.cpp

This is a preliminary work on supporting newer LLVM JIT. Ultimately I think MCJIT is going to be replaced by Orc, however this PR enables basic functions without too much work.
Tested on my Mac running macOS High Sierra and LLVM 6.0.1.

Working LLVM 6.0 support, without CUDA

---

tests/class2.t
tests/lib/golike.t

This PR introduces modified golike.t, which now uses constant expressions for vtables. This has two benefits --- (1) golike.t based code can now be saved to object file and (2) more room for compiler optimizations.

Modified golike.t to work with terralib.saveobj

---

.travis.yml
src/llvmheaders.h
src/llvmheaders_50.h
src/llvmheaders_60.h
src/tcompiler.cpp
src/tcuda.cpp
src/tcwrapper.cpp
src/tllvmutil.cpp

This PR should be able to enable CUDA for LLVM 5 and 6 :)
```
cudaagg.t:
[CUDA] Result size: 2352
cudaaggregate.t:
[CUDA] Result size: 2420
cudaatomic.t:
[CUDA] Result size: 336
CUDA Module:
; ModuleID = 'terra'
source_filename = "terra"
target datalayout = "e-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-unknown-cuda"
; Function Attrs: alwaysinline
define void @bar(i32*) #0 {
entry:
%1 = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
call void asm sideeffect "red.global.max.u32 [$0], $1;", "l,r"(i32* %0, i32 %1)
ret void
}
; Function Attrs: nounwind readnone
declare i32 @llvm.nvvm.read.ptx.sreg.tid.x() #1
; Function Attrs: nounwind
declare void @llvm.stackprotector(i8*, i8**) #2
attributes #0 = { alwaysinline }
attributes #1 = { nounwind readnone }
attributes #2 = { …
```

Support CUDA for LLVM 5 and 6 using LLVM's NVPTX backend

---

src/tdebug.cpp

This is the minimum change required to build on NVIDIA Xavier ( linux4tegra on aarch64 ) in addition to setting the luajit version to 2.1 ( I used beta3 )
When using CMAKE I also have to disable LLVM_ENABLE_RTTI 
I have not yet been able to get CUDA (10) to work, even though it appears to build with cuda when the makefile.inc is configured.

build on aarch64 (nvidia xavier)

---

travis.sh

GNU Tar 1.31 appears to have a bug which results in a crash when extracting CUDA on macOS. Workaround the bug for now by reverting to 1.30.

Fix CUDA installation failure on Travis with macOS

---

src/tcompiler.cpp
src/tcompiler.h
src/tcompilerstate.h
src/tcwrapper.cpp
src/terra.cpp
src/terrastate.h

This patch will allow us to import a type once using `terralib.includec` and use it in code generated for all compilation targets (e.g. both CPU and GPU functions). I expect this will solve #199, and help with some of the issues in #288. It will also allow Regent's CUDA codegen to handle imported structs.

Search for imported structs across all compilation targets

---

Makefile

See: https://github.com/LuaJIT/LuaJIT/issues/484
Can be reverted when the following PR is merged:
https://github.com/LuaJIT/LuaJIT/pull/485

Workaround for macOS Mojave 10.14 link error in LuaJIT

---

src/llvmheaders.h

Apparently the LLVM team decided to release a version 7.1, which breaks all our assumptions that releases >= 5 are numbered X.0.

Fix for LLVM 7.1

---

src/terralib.lua

Compile functions when calling `printstats`

---

src/tcompiler.cpp
src/terralib.lua
tests/noreturn.t

Terra supports marking functions as always-inline, never-inline, and don't-optimize. LLVM also supports marking functions as noreturn. This PR exposes LLVM's noreturn attribute to Terra.

Add support for noreturn functions

---

Makefile
msvc/Makefile
src/CMakeLists.txt
src/asdl.lua
src/terra.cpp
src/terralist.lua
tests/list.t

Partially conflicts with #347, but we'll sort that out later.

Merge terralist.lua from the develop branch

---

appveyor.yml
src/MSVCSetupAPI.h
src/tcompiler.cpp
src/terra.cpp
src/terralib.lua

This commit correctly finds all versions of Visual Studio back to 2010, at least in theory. It first replaces the old method of finding a registry value with a proper implementation of a registry key query and uses that to find either the 8.1 or 10.0 version of the Windows SDK. It then adds an entire header file and function that wades through the sheer insanity that is the Visual Studio COM object setup, which attempts to find either 2017, 2019, or any future version. If this fails, it falls back to the registry method to query visual studio versions all the way back to 2010. Hopefully the directory structure didn't change past 2013, because if it did this won't work.
The native tools detection is kept intact, because if Microsoft loses their mind again and changes everything in a future …

End Visual Studio's reign of terror once and for all

---

src/tcwrapper.cpp
src/tllvmutil.cpp
tests/benchmark_fannkuchredux.t
tests/benchmark_nbody.t
tests/run
tests/speed.t

This fixes #401 by compensating for what is probably an LLVM bug in `copyAttributesFrom` which doesn't actually copy over the `comdat` attributes. Either that, or LLVM doesn't consider `comdat` a traditional attribute. The actual fix here is a single line of code: `newfn->setComdat(fn->getComdat());`. Everything else is either just to improve MSVC compatibility, or is the stdio workaround being removed from the tests.
A separate bug may need to be filed upstream to LLVM.

Fix stdio.h include problem

---

.travis.yml
docker/Dockerfile.ubuntu
docker/build.sh
travis.sh

Hopefully this will help us sanity check that our install procedures are working and that there are no dependencies being hidden by Travis's magic. It might also help as a starting point if we ever needed to move to another CI...

Add Docker build and test in Travis for Ubuntu 16.04, 18.04, 19.10

---

.travis.yml

Otherwise these tests just take too long to run, especially with the growth of LLVM versions Terra supports.

Prune the set of Travis configurations

---

src/terralib.lua
tests/vararg.t

It turns out that Terra can actually forward varargs if you allow vararg function definitions, by using LLVM's built-in `va_list` intrinsics. Here is an example of a logging function:
```
local va_start = terralib.intrinsic("llvm.va_start", {&int8} -> {})
local va_end = terralib.intrinsic("llvm.va_end", {&int8} -> {})
terra Log(level : int, f : rawstring, ...) : {}
if level >= 0 then
C.printf(Levels[level])
end
var vl : C.va_list
va_start([&int8](&vl))
C.vprintf(f, vl)
va_end([&int8](&vl))
C.printf("\n");
end
```
It may be possible to extract individual arguments out, but I haven't attempted to use LLVM's `va_arg` intrinsic, and Terra might not like it. This change simply forwards the varargs state to the function definition.

Allow vararg function definitions

---

src/tdebug.cpp

Depends on https://github.com/terralang/terra/pull/452.
Now that we have Moonjit support, we can finally officially support PPC64le.

PowerPC support

---

src/main.cpp

Windows [ignores the unhandled exception filter](https://peteronprogramming.wordpress.com/2017/07/30/crashes-you-cant-handle-easily-3-status_heap_corruption-on-windows/) for heap corruption, which results in `terra.exe` simply silently crashing if heap corruption is encountered. This adds a super special exception handler to actually catch the heap corruption and grab the stack trace (which unfortunately isn't very useful but we can at least tell the user what happened instead of silently crashing).

Catch heap corruption on windows

---

CHANGES.md
release/share/terra/README.md

This formally marks LLVM versions 3.5-3.7 deprecated, as per https://github.com/terralang/terra/issues/456.
No code changes yet, but anticipate that code support will be removed in approximately 6 months.

Mark LLVM versions 3.5-3.7 as deprecated

---

.github/workflows/main.yml
CMakeLists.txt
Makefile
src/llvmheaders.h
src/llvmheaders_100.h
src/llvmheaders_110.h
src/tcompiler.cpp
src/tcuda.cpp
src/tcwrapper.cpp
src/terra.cpp
src/tinline.cpp
src/tllvmutil.cpp
tests/dgemm3.t
tests/dgemmpaper.t
tests/diffuse.t
tests/expvec.t
tests/gemm.t
tests/sgemm3.t
tests/strerror.t
travis.sh

This should now be working. There is a list of caveats below, but it's close enough that I'm going to merge and track remaining failures via issues.
Known issues at time of merge:
* https://github.com/terralang/terra/issues/476 cannot include immintrin.h
* https://github.com/terralang/terra/issues/477 test failures in LLVM 11 when dynamically linked
* ~https://github.com/terralang/terra/issues/478 doesn't build on macOS with LLVM >= 10~
* https://github.com/terralang/terra/issues/479 tests fail on macOS with LLVM >= 10

Support for LLVM 10 and 11

---

src/tcuda.cpp

Looks like you now need to use explicit LLVM string to std::string conversions.  I tested this with both LLVM 10.x and 11.x and all tests passed.  Did not check older versions of LLVM.
Building terra w/ GCC 10.2 failed due to the patches lines.

Additional fixes for LLVM 11.x (11.1) support 

---

release/include/terra/terra.h
src/main.cpp
src/tcompiler.cpp
src/terra.cpp

Removing more dead code thanks to the removal of LLVM <= 3.7 support.

Remove -m flag because MCJIT is now mandatory

---

src/tcompiler.cpp

This is an incremental change, isolating the fix for identifying the linker properly, and the work around for the bug in LLVM's CPU detection.

Fix linker detection and workaround CPU detection

---

src/tcompiler.cpp
tests/boolcast.t

This appears to fix #460. In the function without `not`, the argument is converted from `int32` to logical `int8` to `bool`. In the function with `not`, the argument is converted from `int32` to logical `int8`, the `not` operator is applied, and the result is converted from logical `int8` to `bool`; the operator ensures that only 0 or 1 will be converted to `bool`. The incorrect results are caused by primitive values being truncated when converted to smaller logical primitive types, instead of being compared against 0.
In this commit, the change in `emitPrimitiveCast` fixes the `int32` to logical `int8` conversion, so that `[bool](256)` does not equal `false`. Similarly, the change in `ConvertPrimitive` fixes the logical `int8` to `bool` conversion, so that `[bool](2)` does not equal …

Fix conversions to logical primitive types

---

.github/workflows/main.yml
travis.sh

Partly this is to keep us (mostly) off of unsupported Ubuntu releases, and partly this helps pave the way for LLVM 12.

Update CI tests (except for LLVM 3.8) to Ubuntu 18.04

---

.github/workflows/main.yml
docker/Dockerfile.ubuntu
travis.sh

As best I can tell, a packaging bug in the official LLVM 13.0.1 binaries broke the CI. Unfortunately the Apt mirror for LLVM does not provide old versions, so we can't downgrade. I am moving the LLVM 13 tests into Docker for the time being so that we can take advantage of LLVM 13 in the official Ubuntu package repository for Ubuntu 21.10.
Once Ubuntu 22.04 is released and made available via Github Actions, that will probably make it possible to move back. Alternatively, maybe this is the signal that I should be moving more tests into Docker....
Also includes some minor refactoring to make future Ubuntu upgrades easier.

Move LLVM 13 tests to Docker to fix CI

---

docs/api.md
src/llvmheaders_100.h
src/llvmheaders_110.h
src/llvmheaders_120.h
src/llvmheaders_130.h
src/llvmheaders_38.h
src/llvmheaders_39.h
src/llvmheaders_50.h
src/llvmheaders_60.h
src/llvmheaders_70.h
src/llvmheaders_80.h
src/llvmheaders_90.h
src/tcompiler.cpp
src/terralib.lua
tests/amdgpu_kernel.t

Needed to be able to correctly generate AMD GPU kernels, among other things.

Add support for setting calling convention on functions

---

src/tcompiler.cpp
tests/amdgpu_kernel.t

When using `emitStore`, use the address space of the provided address rather than assuming `0`. This impacts targets such as AMD GPU where the default address space for allocas is non-zero.

Respect the address space of the storage pointer in emitStore

---

src/tcompiler.cpp
tests/amdgpu_kernel.t

Fixing another pattern that requires the correct use of address spaces.

Fix incorrect use of address space in aggregate parameters

---

src/tcompiler.cpp
tests/amdgpu_kernel.t

AMDGPU backend requires the use of `C_AGGREGATE_REG` (i.e., exploding a struct into its component fields) calling convention rather than `C_AGGREGATE_MEM` (i.e., using `byval` and `sret` to pass the struct on the stack). This change checks the target machine and generates the correct code in the AMDGPU case.
Arguably, this was intended to be done within `CCallingConv` itself, but that would be a larger change and would also involve potentially a lot of code duplication. I do not attempt to do that in this change.
I also modified `C_AGGREGATE_REG` to correctly handle nested structs, which otherwise are not properly exploded. (The previous code unwrapped only one level of the struct.)
Contains one other typo fix for aggregate stores to make sure we use the right address space.

Fixes for AMDGPU calling convention

---

docs/api.md
src/tcompiler.cpp
src/terralib.lua
src/tkind.h
tests/atomicrmw.t
tests/fails/atomicrmw.t
tests/fails/atomicrmw2.t
tests/fails/atomicrmw3.t
tests/fails/atomicrmw4.t
tests/fails/attrload3.t

This is needed for atomics on AMDGPU, but it should also fix a long-standing deficiency with CUDA where we haven't able to use proper atomics since we upgraded from NVVM to NVPTX in LLVM 3.8.

Support for AtomicRMW instruction

---

default.nix

Not trying to make this too pretty because I understand this will change again in the near future with the [Nix redist packages](https://discourse.nixos.org/t/best-practice-for-referencing-cudatoolkit/18710). At least it unblocks our CI.
Fixes #532 .

Fix Nix unstable build in CI

---

.github/workflows/main.yml

Seems to be working now, so re-enable these tests. Previously disabled in #490 to fix the CI.
Fixes #477.

Turn LLVM 9 and 10 dynamic tests back on

---

.github/workflows/main.yml
docker/Dockerfile.ubuntu
docker/Dockerfile.ubuntu-prebuilt
docker/Dockerfile.ubuntu-source
docker/Dockerfile.ubuntu-source-test
docker/Dockerfile.ubuntu-test
docker/build.sh
docker/install_cuda.sh
release/share/terra/README.md
travis.sh

This PR includes (or will include) a number of changes:
[1]: There is no recent Mac hardware that includes NVIDIA GPUs, and based on Apple's direction I don't believe it's likely to come back any time soon. We already removed it from CI a while ago, and the CUDA process was always clunky, so maintainin the dead code just doesn't seem worth it.

Release configuration updates

---

src/cudalib.lua
src/terralib.lua

This is to avoid dependency on LLVM NVPTX backend when it's not needed (when CUDA code generation is not enabled/used).
Fixes #446.

Initialize CUDA target lazily

---

default.nix

As described in [this thread](https://discourse.nixos.org/t/best-practice-for-referencing-cudatoolkit/18710), NixOS unstable is moving toward splitting the CUDA packages up into multiple pieces. This updates our Nix derivation so that hopefully we stay away from the breakage as the deprecate the old way of doing things.

Upgrade to the newer split packages in NixOS unstable

---

docker/install_cuda.sh
src/tcompiler.cpp
tests/amdgpu_kernel.t

On targets like AMDGPU where stack variables have a default address space, we need to be careful that the address of operator returns a pointer of the expected type (rather than blindly passing back the pointer it gets as the address).
This means that a stack variable `x` in AMDGPU will live in address space `5`, but when we do `&x` we return a pointer with address space `0` (i.e., a generic pointer). This requires an `addrspacecast` in the Terra backend.
One might wonder whether it would be better to make `&x` return `terralib.types.pointer(int, 5)` (i.e., pointer to addrspace `5`), but if we did this Terra functions would become target-specific. It would be impossible to even type check a function without having the target defined. So I think the only sensible approach is to make `&` …

Fix address of on targets with a non-generic default addrspace

---

src/cudalib.lua

This is a follow-on to #547 which fixes a long-standing hack in the CUDA backend which is no longer necessary.
It used to be that an expression like `&gv` would incorrectly return a type of `terralib.types.pointer(T, 0)` if `T` was the type of `gv`, even if `gv` was located in a non-generic address space. This happens in CUDA where shared memory and constants are both located in non-generic address spaces. So then we'd get an LLVM expression of type `terralib.types.pointer(T, 3)` but Terra thought the type was `terralib.types.pointer(T, 0)`.
It looks like the old `cudalib.lua` just papered over the top of this by casting the address space back (a no-op in LLVM, but needed for Terra to understand the correct type), then using NVVM intrinsics to cast it away again (followed by another Terra …

Fix CUDA: no longer need explicit addrspace casts

---

src/tcompiler.cpp
tests/amdgpu_struct.t

This is a problem that shows up in the AMD GPU backend, but I think it may also fix a related problem in CUDA (and other targets).
Structs imported via `terralib.includec` track the defining target/function, and use this to reconstitute the correct type when used later. This is not correct when generating code for a different target. So we should really only reuse the struct when the target matches.

Fix for use of C structs in different target from the defining one

---

travis.sh

The Windows CI seems to have broken; best guess is that MSVC got upgraded and something is now incompatible. I'm hoping a newer binary build of LLVM will fix it.

Upgrade to a newer set of binaries that fix Windows build

---

.github/workflows/main.yml
CHANGES.md
Makefile
release/share/terra/README.md
src/llvmheaders.h
src/llvmheaders_140.h
src/tcompiler.cpp
src/tllvmutil.cpp
travis.sh

At some point we need to come back and seriously think about how to architect the compiler for opaque pointers. But for now, non-opaque pointers aren't gone yet, so we'll just take advantage of that to get by.
Passes on my local machine.

Add support for LLVM 14

---

CHANGES.md
release/share/terra/README.md

This is the formal deprecation of LLVM <= 5, per #471.
No code removals. Only documentation changes at this time.

Deprecate LLVM <= 5

---

CHANGES.md
STABILITY.md

For Terra 1.0.0, we plan to adopt a stability policy to set expectations on what changes may be expected, and how those changes will be communicated (e.g., in the version number). This PR includes my proposal for this stability policy. Feedback is welcome! Please comment on this PR if you see anything that is unclear, missing, or seems unreasonable.
You can see a rendered version here: https://github.com/elliottslaughter/terra/blob/stability/STABILITY.md

Add stability policy

---

cmake/Modules/GetLuaJIT.cmake
default.nix

I'm splitting this out from #566 to be tested separately. Newer LuaJIT has fixes for ARM64 needed to run Terra, but may also provide benefits on other platforms.
I'm also changing the default Lua back to LuaJIT on all platforms except PPC64le, since Moonjit has been archived. PPC64le is the only architecture where we really can't drop support for it.

Update LuaJIT and set default (except on PPC64le)

---

src/tcompiler.cpp
tests/cconv_more.t

As best I can tell, the PPC64le calling convention mostly mirrors x86 except that it has a special case for passing structs of all-`float` or all-`double` values via registers. This PR fixes this hole in the PPC64le calling convention and also does a bit of minor refactoring in the calling convention code generally (though a larger refactoring is still being pushed down the road). In general this is trying to move in the direction of using the target to determine what the calling convention should be, rather than having code paths delimited by static `ifdef`s that by nature refer to the host only.
It also adds what is (I hope) a much more comprehensive test for calling conventions, at least along a number of axes, in particular testing uniform structs with up to 9 values of types `int8`, …

Fix PPC64le calling convention for structs of all-float or all-double values

---

GNUmakefile
src/CMakeLists.txt
tests/dynlib.t

Historically Terra has installed itself as `terra.so` on Unix, even though the system convention would be `libterra.so`. I believe at the time the reason was for compatibility with Lua, where modules are expected to be unprefixed (e.g., you can `require("terra")` to load `terra.so` automatically).
We don't currently have a test case for this, but you can verify this behavior manually with (after a build):
```
$ cd lib
$ ../luajit/bin/luajit-2.1.0-beta3 
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2022 Mike Pall. https://luajit.org/
JIT: ON SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> require("terra")
> 
```
This change makes `libterra.so` the default in CMake, but adds a target to symlink this to `terra.so` for compatibility with the Lua convention. This should benefit …

Install libterra.so with system-standard name and symlink terra.so for other users

---

src/tcompiler.cpp
tests/cconv_more.t

This PR includes substantial fixes to the PPC64le calling convention for passing structs. In particular, PPC64le now passes the `cconv.t` test, as well as `cconv_more.t` (which is substantially upgraded in this PR).
The test `cconv_more.t` has been upgraded to use metaprogramming, so that it's easier to extend and modify parameters. In particular the test covers:
* Functions with `N` scalar arguments (where `N` can be as high as 22, though it defaults to 12 for speed in the CI) for types `int8`, `int16`, `int32`, `int64`, `float`, `double` as well as `T[2]` for all the above types.
* Same, but with a struct of `N` fields as a single argument.
* Same, but with two arguments of this struct type instead of one.
* Same as the above three cases, but with various rotations through sets of types …

More fixes for PPC64le calling convention

---

src/tcompiler.cpp
tests/cconv_array.t

Terra supports the ability to pass arrays by value. While this is outside of the scope of the C calling convention, we should at least confirm that Terra does so self-consistently.
This PR adds a fix for PPC64le in this case, and a corresponding test to make sure we're covering this behavior in the test suite.

Fix for passing arrays by value in PPC64le

---

src/tcompiler.cpp

After this change, I get:
```
=================
= FAILING tests
=================
constanttypes.t
coverage3.t
multiterra.t
vecobj.t
=================
545 tests passed. 4 tests failed.
```
It seems this didn't matter for the C calling convention, but it does matter for calling intrinsics that return void, where LLVM has stricter type checking.

Fix void return in PPC64le calling convention

---

src/terralib.lua

Terra seems to rely on [this code path](https://github.com/terralang/terra/blob/5bb16734ff1ce6afe00cd56be2670dae04531f6a/src/terralib.lua#L4883-L4898) being executed to initialize some type cache machinery. This currently happens only on platforms where debug info is enabled (i.e., x86 only). Therefore on PPC64le, this initialization does not happen, leading to errors down the line.
For now, make sure that initialization is in place so that we don't depend on the user doing `terralib.cast(uint64, 1ULL)` or similar to make their programs work.

Fix for type cache initialization on PPC64le

---

tests/coverage3.t

This test has been known to [fail on Windows](https://github.com/terralang/terra/issues/287), but I hadn't had time to debug it properly. It also fails on PPC64le.
The error message seems to originate from LuaJIT (in this case, Moonjit): https://github.com/moonjit/moonjit/blob/eb7168839138591e0d2a1751122966603a8b87c8/src/lj_errmsg.h#L179
Therefore it seems this is simply unimplemented behavior in LuaJIT/Moonjit, and therefore there is not much we can do about it from our end.
This PR shuts off the test on PPC64le.

Disable coverage3.t on PPC64le

---

tests/multiterra.t

See  #583 for rationale and discussion.
This is the last outstanding test for PPC64le.

Disable multiterra.t on PPC64le

---

GNUmakefile
src/CMakeLists.txt

This commit removes the addition of the `-pagezero_size` and `-image_base` linker flags.

Fix executables built on arm64 macOS

---

.github/workflows/main.yml
travis.sh

GitHub Actions is removing support for 10.15.
https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/

Upgrade CI to macOS 11

---

docs/Gemfile
docs/Gemfile.lock
docs/getting-started.md
release/share/terra/README.md
tests/dynlib.t

One test and some docs still had references to the (now unnecessary) `-pagezero_size 10000 -image_base 100000000` flags.

More cleanup for unnecessary macOS linker flags

---

src/tcompiler.cpp
tests/cconv_array.t
tests/cconv_more.t

See #594 for reproducer. AArch64 does not use `byval` on parameters passed by memory and instead uses `noundef` (though the latter is probably just an optimization).

Fix calling convention in AArch64 for large structs

---

.cirrus.yml
.github/workflows/main.yml
CHANGES.md
docker/install_script_multiarch.sh
tests/class.t
tests/class6.t
tests/coverage3.t
tests/vecobj.t

Does not pass yet, so I won't merge, but this PR can be used to track pass rate for ARM on actual hardware (whereas emulation seems to suffer from additional failures beyond what ARM hardware experiences).

Add CI for AArch64 via Cirrus

---

src/tcompiler.cpp

Potential fix for macOS on M1: https://github.com/terralang/terra/issues/597#issuecomment-1221319348.

Only include formal parameters in function for varargs call

---

tests/atomicrmw.t

Shouldn't have a functional impact, but makes the output less confusing.

Fix a typo in atomicrmw.t test

---

src/tcwrapper.cpp

See #605 for failure mode and justification for this change.

Fix target ABI for macOS M1 by reading arguments from BuildCompilation

---

src/terralib.lua
tests/atomicrmw.t

So we're going to disallow it. This seems to be a case where LLVM's documentation does not match LLVM's implementation.
This is a breaking change. That's ok because:
* The feature is experimental.
* Any code that used the feature will hit a compile error (i.e., there will be no silent breaking changes).
* Practically speaking, the number of users who use this is probably nil.

LLVM does not allow xchg on pointers

---

tests/cconv_array.t

This is a workaround for #604. LuaJIT does not support more than 8 `int8` parameters, so we're just going to have to live with this until that is addressed.

Limit cconv_array.t on macOS M1 with int8 to 8 parameters

---

.gitlab-ci.yml
tests/cconv_more.t

You can see the CI instance at https://code.ornl.gov/ecpcitest/csc335/terra/-/pipelines .
Because of the way things are set up, this will not, unfortunately, run on PRs or commits. But I can configure the CI to run regularly so that we can ensure PPC64le builds continue to work.
This is also, by the way, our first CI coverage with CUDA using actual GPUs.

Enable CI on PPC64le via Ascent

---

tests/cconv_array.t

Only run cconv_array.t for int16, int32, float up to 8 on macOS M1

---

src/tcompiler.cpp

Fixes, under wasm32- and wasm64- triples, how terra passes aggregates by
value, to match clang/emscripten.
WebAssembly only passes single-value structs directly in registers [1], all other
structs (and all arrays) are passed indirectly.
It would be nice to have tests for this but I'm not really sure how to go about
creating them without pulling in a webassembly VM or Emscripten as
dependencies. This does allow my terra->wasm code to link against 
clang/Emscripten compiled libraries, for what it's worth.
[1] https://github.com/WebAssembly/tool-conventions/blob/main/BasicCABI.md

WebAssembly (wasm32/64) Calling Convention Fix

---

GNUmakefile
cmake/Modules/FindClang.cmake

Apparently Clang decided to switch to using major version only starting in version 16.
Also fixed the Makefile to match.

Fix resource path in LLVM 16.

---

.cirrus.yml

The LLVM 14 package seems to be missing for some reason, so let's see if we can work around it.

Upgrade FreeBSD to fix CI

---

tests/bug.t
tests/lib/objc.t

Apparently, on macOS the Objective-C headers now require `-fblocks`. Testing here to make sure that'll fly in macOS 11.

Fixes for macOS 13 Objective-C header files

---

src/tcuda.cpp

Remove call TargetMachine::adjustPassManager which is gone in LLVM 16

---

tests/cconv_more.t

Work around cconv_more.t failure on Apple M2 by setting N=9

---

src/tcompiler.cpp
src/tllvmutil.cpp

This is the first part of the migration toward opaque pointers (#553). Starting with the easy cases, I'm trying to reduce the compiler's reliance on looking up pointee types. But this PR may not get 100% of all the cases.

Modernize use of LLVM pointer types

---

.cirrus.yml
.github/workflows/main.yml
CHANGES.md
src/CMakeLists.txt
src/llvmheaders.h
src/llvmheaders_170.h
src/tcompiler.cpp
src/tcompilerstate.h
src/tcuda.cpp
src/tcwrapper.cpp
src/tllvmutil.cpp
src/tllvmutil.h
tests/compile_time_array.t
tests/compile_time_array2.t
tests/constantinits.t
tests/dgemm3.t
tests/dgemmpaper.t
tests/diffuse.t
tests/gemm.t
tests/sgemm3.t
travis.sh

This rolls up the changes in #641 and then adds more on top to adapt to the removal of the legacy pass manager in LLVM 17. Overall, this seems to be working dramatically better than LLVM 15-16, so I have updated the opaque pointer version bounds to be LLVM 17-only.
Running the test suite locally (macOS x86) produces one test failure:
```
99% tests passed, 1 tests failed out of 550
Total Test time (real) = 143.88 sec
The following tests FAILED:
71 - classifyfloatstructs.t (Failed)
Errors while running CTest
```
For once I'm actually done with this ahead of the LLVM 17 final release (above results were with rc4), so I can't merge this until the final release gets cut. But things are looking good overall.
Known issues:
* Compile time regressions in `compile_time_array.t` and …

Add support for LLVM 17

---

.github/workflows/main.yml
default.nix

Nix has removed LLVM 11 so we need to move to a newer version.
This removes Linux AArch64 support in Nix because that still requires LLVM 11. You can downgrade Nix to an older version to get the LLVM 11 package to restore this support, but we will not be maintaining it here.

Update Nix build to use LLVM 13

---

.github/workflows/main.yml

GitHub has deprecated macOS 11 in CI, so bump up to 12 before it gets removed.

Bump macOS in CI to 12

---

src/lparser.cpp
src/tcwrapper.cpp
src/terra.cpp

I've audited these, and I don't think they would have caused issues, but `sprintf` is still bad all around so better to avoid it.

Switch to snprintf throughout codebase

---

src/tcompiler.cpp
src/terralib.lua
tests/addressspace.t

This is a new approach to the work we originally began in #469. Since the last time we put effort into this, Intel integrated a SPIR-V target directly into LLVM itself. The new target was first available in LLVM 15 and has improved dramatically over the last few releases.
Therefore, this puts us on a much better footing than #469 which fundamentally relied on some infrastructure in Clang (because the corresponding LLVM target did not actually exist and it was faked entirely on the Clang side).
I'm currently in the process of verifying that this new SPIR-V support works and is able to generate code that is compatible with, say, OpenCL.

Support for SPIR-V code generation

---

src/lparser.cpp

Fixes an out-of-bounds read reported by Address Sanitizer on macOS x86 with LLVM 17.

Fix read out of bounds with empty file

---

.github/workflows/main.yml
release/share/terra/README.md
travis.sh

* Update Linux compat test to use LLVM 18 and test on Ubuntu 24.04
* ~Add Ubuntu 24.04 package test for LLVM 18~ (not working, we'll have to add this later)
* Update macOS to release LLVM 18
* Update README instructions and guidance

Update release packages to use LLVM 18

---

.github/workflows/main.yml
travis.sh

This should also enable binaries to be included in the next release.
Note that runs under `macos-14` run on M1 hardware, whereas previous macOS versions run on x86 hardware. This is a GitHub-specific decision and not specific to the way that macOS works (macOS 14 still runs fine on x86).

Run GitHub Actions CI on macOS M1

---

src/tcompiler.cpp
tests/avx512.t

Many modern CPUs support AVX512 with 512 bit wide vector instructions. Currently, terra only enables AVX extensions (256 bit) for its `vector` type. This PR enables basic AVX512 features if the host CPU supports it.
This potentially speeds up computations with the `vector` type by factor of 2 as twice as many instructions can be handled at the same time.
None as the old code path (AVX only) is used if the CPU does not support all required AVX512 instruction sets.

Add AVX512 support

---

.github/workflows/main.yml

According to a recent email announcement:
> The macOS 12 runner image will be removed by December 3rd, 2024.
So we're bumping up to macOS 13.
Not sure what we'll do when they remove the last x86 OS version, but we'll cross that bridge when we get there.

Bump CI to macOS 13

---

docs/api.md

Thanks to @alliby for the fix.

Fix typo in API documentation

---

.cirrus.yml

Apparently 14.0 isn't available anymore, so bumping up to 14.2.
https://cirrus-ci.org/guide/FreeBSD/#list-of-available-image-families

Fix FreeBSD version for CI

---

.github/workflows/main.yml
docker/install_cuda.sh

Initial exploration of alternatives in #685 has been unsuccessful, so switch ARM64 jobs over to native hardware and disable emulated multiarch jobs for now. Perhaps we'll find a solution at some point, but I suspect a QEMU bug is causing crashes in GCC.
* Enables compatibility test for ARM64:
* Ubuntu 20.04 base build
* CUDA 12.2
* Tested up to Ubuntu 22.04
* Ubuntu 24.04 fails to parse NEON headers, probably gated on LLVM version
* x86 build for Ubuntu 20.04 requires a rebuild of LLVM binaries, so defer that for now
* But do upgrade CUDA to 12.1 so we're on something less ancient

Disable emulated multiarch and switch to native ARM runners
