tests/lib/matrixtestharness.t
The stride in the first matrix is K (not k). 
The second nested loop should be generating random numbers to B.
=> fixing matrix index

Makefile
Seems to build ok on OSX 10.10.5 (clang+llvm-3.5.2) as well.
=> changes to support Linux (Debian-based distros, at least)

.gitignore, Makefile, src/lobject.cpp, src/lparser.cpp, src/main.cpp, src/tcompiler.cpp, src/tdebug.cpp, src/terra.cpp, src/terrastate.h, src/tobj.h
Builds with -Werror on both Linux (gcc 4.8.5, clang 3.5) and OSX (clang 3.5.2).
=> clean up a bunch compiler warnings

release/share/terra/README.md
I've deleted a redundant "download the" in the README.
=> Small typo fix in README.

Makefile
This change makes it easier to use LLVM-enabled third-party libraries (e.g. Legion) in terra applications.
Starting with LLVM 3.6+, it's a fatal error to have two copies of some of the LLVM objects in the same process, but it's hard to have a third-party library use the LLVM code that has been imported into terra
because the terra build includes only the portions of the libraries it needs.
With this change, the default build remains the same, but if the REEXPORT_LLVM_COMPONENTS
variable is set by the caller, any libraries needed for that component (i.e. the result of 
`llvm-config --libs ${REEXPORT_LLVM_COMPONENTS}`) are included in the terra binary in their entirety.
=> build: optionally re-export some/all LLVM components

src/tcompiler.cpp
Moved from https://github.com/StanfordLegion/terra/pull/2
=> Create anonymous structs to avoid non-deterministic renaming

Makefile
=> Fix order of Terra redirects causing output not to get captured on stderr

src/tcompiler.cpp
On Skylake processors, Clang 3.8.x generates illegal AVX instructions.  Therefore we disable AVX code generation entirely in that situation.  More information can be found on this bug discussion:
https://www.bountysource.com/issues/37851678-llvm-3-8-1-compiles-vmovsd-on-intel-skylake-using-evex
=> Workaround for Skylake-Clang 3.8 Bug

src/tcompiler.cpp, tests/bug372.t
=> Fix bug #372

src/tcompiler.cpp, tests/bug372.t, tests/bug372b.t
Thanks again to @seemamirch  for the patch.
=> Second attempt to fix bug #372

src/tcompiler.cpp, tests/bug372_perf.t, tests/bug372c.t, tests/bug372d.t
Thanks again to Seema Mirchandaney.
This should be (finally) a complete fix for #372, assuming no more corner cases are found.
This PR supersedes #390 and should be strictly more correct and have strictly better compile time.
=> Fix bugs in struct (attr)load and (attr)store, and compile time regression

src/tcompiler.cpp, tests/compile_time_array.t, tests/compile_time_array2.t, tests/compile_time_array3.t
Thanks to @seemamirch for the fix.
=> Fix bug #427 (try 2)

src/terralib.lua
Moved the new check for cudahome to after where it could be initialized.
=> Re-enabled cuda support.

.github/workflows/main.yml
I didn't realize this has to be turned on explicitly.
=> Run Github Actions on PRs

.github/workflows/main.yml, release/share/terra/README.md, src/terralib.lua, travis.sh
Fixes #479 .
It feels like a hack, but it seems to be working so I'm going to take it unless someone comes up with a better solution.
=> Fix includec on macOS with LLVM >= 10

release/share/terra/README.md, src/terralib.lua, tests/expvec.t
=> Set GNU C version on all non-Windows platforms

travis.sh
Testing to see if the compiler workaround noted in https://github.com/terralang/terra/issues/365#issuecomment-618512629 is still necessary.
=> Disable macOS compile workaround

.github/workflows/main.yml, src/tcompiler.cpp
=> Fix some LLVM deprecation warnings

.github/workflows/main.yml
=> Try downgrading dynamic test to LLVM 8

src/terralib.lua
This adds a "slimtrace" option that can be toggled the same way as "fulltrace", which removes all `terralib.lua` lines from stack traces so you can inspect what went wrong in *your* code instead of terra's code. Example:
```
Terra -- A low-level counterpart to Lua
Release 1.0.0-beta3-16-g560bae8
Stanford University
zdevito@stanford.edu
> terra asdf() [error("blah")] end
...ments/Visual Studio 2019/Projects/terra/src/terralib.lua:423: blah
stack traceback:
[C]: in function 'userfn'
[string "stdin"]:1: Errors reported during evaluating Lua code from Terra
...ments/Visual Studio 2019/Projects/terra/src/terralib.lua:1804: in function 'evalluaexpression'
...ments/Visual Studio 2019/Projects/terra/src/terralib.lua:2831: in function 'docheck'
...ments/Visual Studio …
```
=> Add slimtrace

src/tcuda.cpp
=> Enable LLVM inliner in NVPTX code path

CHANGES.md, docs/api.md, src/tcompiler.cpp, src/terralib.lua, src/tkind.h, tests/atomicrmw.t
Needed to issue correct barriers on AMDGPU (among other things).
Also updates some documentation to include things that have been in Terra for a while.
=> Add support for fence instructions

.gitignore, docs/api.md, src/tcompiler.cpp, src/terralib.lua, src/tkind.h, tests/cmpxchg.t
=> Add support for atomic compare and exchange instruction

src/tcompiler.cpp
This migrates us onto newer APIs sooner, and helps make it more obvious when older code paths can be deleted.
I reviewed `tcompiler.cpp` in this PR.
=> Minimize LLVM version bounds

tests/vecobj.t
This is a workaround for the Moonjit limitations described in #581. With these changes, vecobj.t passes.
Test suite status after this PR:
```
=================
= FAILING tests
=================
multiterra.t
=================
548 tests passed. 1 tests failed.
```
=> Fix vecobj.t test on PPC64le

src/tcompiler.cpp
Initial commit is a first pass, will clean up once I confirm it's working.
=> Fix C calling convention on AArch64

CHANGES.md, default.nix
Last stop before releasing 1.1.1.
=> Bump version to 1.1.1 and prepare release notes

src/tcompiler.cpp
=> Fix Windows CI build

tests/fakeasm.t
Trying to fix the crash seen e.g. here: https://github.com/terralang/terra/actions/runs/9558834269/job/26348185449
=> Switch fakeasm to use snprintf

.gitignore, release/share/terra/README.md
fixed typo in README.md
added some test artifacts names to ignore list
added .idea and cmake-build-debug to ignore list
=> RAII - pr - auto CI

.github/workflows/main.yml, default.nix
* NixOS 25.05
* Remove NixOS unstable, as it removes all supported LLVM versions (as of this date)
* CUDA 12
=> Upgrade Nix version and dependencies in CI
